---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

Likelihood ratio test is a statistical test for comparing goodness of fit of two statistical models.

Given two models M1 and M2, test statistics ($d$) of the likelihood ratio test is defined as the following: $d = 2 * (log.likelihood(M1) - log.likelihood(M2))$. 

Following the null hypothesis that the two models are not different from each other, distribution of the test statistics $d$ can be approximated by a parametric chi-squared distribution: $\chi^2$. Parameter of the $\chi^2$ distribution (degree of freedom) is the difference of degree of freedoms between the two models, which is also the difference of predictor numbers between the two models.

Below is R code using LRT to compare two Gaussian models:

```{r}
x = rnorm(100, 0, 3)
y = rnorm(100, 0, 3)
plot(x, y)

m1 = glm(y ~ 1)
m2 = glm(y ~ 1 + x)

d = 2 * (logLik(m2) - logLik(m1))

p.val = 1 - pchisq(d, df = 1)
# result suggest m2 is not better than m1. In another word, x is not associated with y. 
```

In the Roche setup, $y$ is the differential effects of each patient under each treatment arms. Specifically, $y = log(pmf1^{t1} / (1 - pmf1^{t1}) - log(pmf1^{t0} / (1 - pmf1^{t0})$ for binary outcome, and $y = beta^{t1} - beta^{t0}$ for time-to-event variables.

$x$ will be any potential biomarkers.

